#
# Builds the docs and deploys to GitHub pages
#
# https://github.com/actions/setup-node
# Using https://github.com/marketplace/actions/deploy-to-github-pages
name: Deploy to Github pages

on:
  push:
    branches:
      - master

jobs:
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'yarn'
    - run: yarn install
    - run: yarn pages:build

    - run: touch .github/pages/dist/.nojekyll
    - name: Deploy pages 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: .github/pages/dist # The folder the action should deploy.
