name: Lint and test

on: [ push, pull_request ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - run: yarn install
      - run: yarn test
      - run: yarn lint
      - run: yarn build
